// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using MCWebApplication1.Areas.Minecraft.Models.EcoData;
//
//    var EcoDataDeserializer = EcoDataDeserializer.FromJson(jsonString);

namespace Highgeek.McWebApp.Common.Models.Adapters.EcoData
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class EcoDataAdapter
    {
        [JsonProperty("ecopets:cheetah_level")]
        public long EcopetsCheetahLevel { get; set; }

        [JsonProperty("ecopets:cheetah_xp")]
        public double EcopetsCheetahXp { get; set; }

        [JsonProperty("ecopets:jackolantern_level")]
        public long EcopetsJackolanternLevel { get; set; }

        [JsonProperty("ecopets:jackolantern_xp")]
        public double EcopetsJackolanternXp { get; set; }

        [JsonProperty("ecopets:rhino_level")]
        public long EcopetsRhinoLevel { get; set; }

        [JsonProperty("ecopets:rhino_xp")]
        public double EcopetsRhinoXp { get; set; }

        [JsonProperty("ecopets:blaze_level")]
        public long EcopetsBlazeLevel { get; set; }

        [JsonProperty("ecopets:blaze_xp")]
        public double EcopetsBlazeXp { get; set; }

        [JsonProperty("ecopets:mancubus_level")]
        public long EcopetsMancubusLevel { get; set; }

        [JsonProperty("ecopets:mancubus_xp")]
        public double EcopetsMancubusXp { get; set; }

        [JsonProperty("ecopets:ravager_level")]
        public long EcopetsRavagerLevel { get; set; }

        [JsonProperty("ecopets:ravager_xp")]
        public double EcopetsRavagerXp { get; set; }

        [JsonProperty("ecopets:sea_serpent_level")]
        public long EcopetsSeaSerpentLevel { get; set; }

        [JsonProperty("ecopets:sea_serpent_xp")]
        public double EcopetsSeaSerpentXp { get; set; }

        [JsonProperty("ecopets:unicorn_xp")]
        public double EcopetsUnicornXp { get; set; }

        [JsonProperty("ecopets:skeleton_xp")]
        public long EcopetsSkeletonXp { get; set; }

        [JsonProperty("ecopets:unicorn_level")]
        public long EcopetsUnicornLevel { get; set; }

        [JsonProperty("ecopets:vampire_level")]
        public long EcopetsVampireLevel { get; set; }

        [JsonProperty("ecopets:vampire_xp")]
        public double EcopetsVampireXp { get; set; }

        [JsonProperty("ecopets:tiger_level")]
        public long EcopetsTigerLevel { get; set; }

        [JsonProperty("ecopets:tiger_xp")]
        public double EcopetsTigerXp { get; set; }

        [JsonProperty("ecopets:skeleton_level")]
        public long EcopetsSkeletonLevel { get; set; }

        [JsonProperty("ecoshop:enchantedbook_ascend_times_bought")]
        public double? EcoshopEnchantedbookAscendTimesBought { get; set; }

        [JsonProperty("ecoshop:dispenser_times_bought")]
        public double? EcoshopDispenserTimesBought { get; set; }

        [JsonProperty("ecoshop:grass_block_times_bought")]
        public double? EcoshopGrassBlockTimesBought { get; set; }

        [JsonProperty("ecoquests:quest_daily_quest_example_has_started")]
        public bool? EcoquestsQuestDailyQuestExampleHasStarted { get; set; }

        [JsonProperty("ecoshop:arrow_times_bought")]
        public double? EcoshopArrowTimesBought { get; set; }

        [JsonProperty("ecoshop:enchantedbook_rumble_times_bought")]
        public double? EcoshopEnchantedbookRumbleTimesBought { get; set; }

        [JsonProperty("ecoskills:enchanting")]
        public double? EcoskillsEnchanting { get; set; }

        [JsonProperty("ecoshop:enchantedbook_metabolism_times_bought")]
        public double? EcoshopEnchantedbookMetabolismTimesBought { get; set; }

        [JsonProperty("ecoskills:woodcutting_xp")]
        public double? EcoskillsWoodcuttingXp { get; set; }

        [JsonProperty("ecoshop:tripwire_hook_times_bought")]
        public double? EcoshopTripwireHookTimesBought { get; set; }

        [JsonProperty("ecoskills:farming")]
        public double? EcoskillsFarming { get; set; }

        [JsonProperty("ecoshop:enchantedbook_escape_times_bought")]
        public double? EcoshopEnchantedbookEscapeTimesBought { get; set; }

        [JsonProperty("ecoskills:dynamic_mining")]
        public double? EcoskillsDynamicMining { get; set; }

        [JsonProperty("ecoshop:enchantedbook_aura_times_bought")]
        public double? EcoshopEnchantedbookAuraTimesBought { get; set; }
#nullable enable
        [JsonProperty("eco:player_name")]
        public string? EcoPlayerName { get; set; }

        [JsonProperty("ecoshop:dropper_times_bought")]
        public double? EcoshopDropperTimesBought { get; set; }

        [JsonProperty("ecoshop:enchantedbook_endaffinity_times_bought")]
        public double? EcoshopEnchantedbookEndaffinityTimesBought { get; set; }

        [JsonProperty("ecoshop:bone_times_bought")]
        public double? EcoshopBoneTimesBought { get; set; }

        [JsonProperty("ecoshop:glowstone_times_bought")]
        public double? EcoshopGlowstoneTimesBought { get; set; }

        [JsonProperty("ecoskills:health")]
        public double? EcoskillsHealth { get; set; }

        [JsonProperty("ecoshop:amethyst_block_times_bought")]
        public double? EcoshopAmethystBlockTimesBought { get; set; }

        [JsonProperty("ecoskills:woodcutting")]
        public double? EcoskillsWoodcutting { get; set; }

        [JsonProperty("ecoshop:stone_bricks_times_bought")]
        public double? EcoshopStoneBricksTimesBought { get; set; }

        [JsonProperty("ecoskills:reimbursement")]
        public double? EcoskillsReimbursement { get; set; }

        [JsonProperty("ecoshop:magma_cream_times_bought")]
        public double? EcoshopMagmaCreamTimesBought { get; set; }

        [JsonProperty("ecoshop:enchantedbook_times_bought")]
        public double? EcoshopEnchantedbookTimesBought { get; set; }

        [JsonProperty("ecoshop:enchantedbook_infernaltouch_times_bought")]
        public double? EcoshopEnchantedbookInfernaltouchTimesBought { get; set; }

        [JsonProperty("ecoshop:diamond_times_bought")]
        public double? EcoshopDiamondTimesBought { get; set; }

        [JsonProperty("ecoskills:acrobatics_xp")]
        public double? EcoskillsAcrobaticsXp { get; set; }

        [JsonProperty("ecoshop:enchantedbook_confusion_times_bought")]
        public double? EcoshopEnchantedbookConfusionTimesBought { get; set; }

        [JsonProperty("ecoshop:white_dye_times_bought")]
        public double? EcoshopWhiteDyeTimesBought { get; set; }

        [JsonProperty("ecoshop:repeater_times_bought")]
        public double? EcoshopRepeaterTimesBought { get; set; }

        [JsonProperty("ecoshop:coal_block_times_bought")]
        public double? EcoshopCoalBlockTimesBought { get; set; }

        [JsonProperty("ecoskills:spelunking")]
        public double? EcoskillsSpelunking { get; set; }

        [JsonProperty("ecoskills:armory")]
        public double? EcoskillsArmory { get; set; }

        [JsonProperty("ecoshop:observer_times_bought")]
        public double? EcoshopObserverTimesBought { get; set; }

        [JsonProperty("ecoskills:master_lumberjack")]
        public double? EcoskillsMasterLumberjack { get; set; }

        [JsonProperty("ecoshop:glow_ink_sac_times_bought")]
        public double? EcoshopGlowInkSacTimesBought { get; set; }

        [JsonProperty("ecoshop:enchantedbook_lumberjack_times_bought")]
        public double? EcoshopEnchantedbookLumberjackTimesBought { get; set; }

        [JsonProperty("ecoshop:dirt_times_bought")]
        public double? EcoshopDirtTimesBought { get; set; }

        [JsonProperty("ecoshop:sand_times_bought")]
        public double? EcoshopSandTimesBought { get; set; }

        [JsonProperty("ecoskills:exploration")]
        public double? EcoskillsExploration { get; set; }

        [JsonProperty("ecoshop:prismarine_bricks_times_bought")]
        public double? EcoshopPrismarineBricksTimesBought { get; set; }

        [JsonProperty("ecoskills:satiation")]
        public double? EcoskillsSatiation { get; set; }

        [JsonProperty("ecoshop:piston_times_bought")]
        public double? EcoshopPistonTimesBought { get; set; }

        [JsonProperty("ecoskills:magnetic_rod")]
        public double? EcoskillsMagneticRod { get; set; }

        [JsonProperty("ecoskills:shamanism")]
        public double? EcoskillsShamanism { get; set; }

        [JsonProperty("ecoskills:strong_impact")]
        public double? EcoskillsStrongImpact { get; set; }

        [JsonProperty("ecoskills:enchanting_xp")]
        public double? EcoskillsEnchantingXp { get; set; }

        [JsonProperty("ecoshop:enchantedbook_haunting_times_bought")]
        public double? EcoshopEnchantedbookHauntingTimesBought { get; set; }

        [JsonProperty("ecoshop:enchantedbook_aracanedefence_times_bought")]
        public double? EcoshopEnchantedbookAracanedefenceTimesBought { get; set; }

        [JsonProperty("ecoskills:second_chance")]
        public double? EcoskillsSecondChance { get; set; }

        [JsonProperty("ecoshop:birch_log_times_bought")]
        public double? EcoshopBirchLogTimesBought { get; set; }

        [JsonProperty("ecoskills:infernal_resistance")]
        public double? EcoskillsInfernalResistance { get; set; }

        [JsonProperty("ecoshop:enchantedbook_fortitude_times_bought")]
        public double? EcoshopEnchantedbookFortitudeTimesBought { get; set; }

        [JsonProperty("ecoshop:amethyst_shard_times_bought")]
        public double? EcoshopAmethystShardTimesBought { get; set; }

        [JsonProperty("ecoshop:iron_ingot_times_bought")]
        public double? EcoshopIronIngotTimesBought { get; set; }

        [JsonProperty("ecoshop:prismarine_times_bought")]
        public double? EcoshopPrismarineTimesBought { get; set; }

        [JsonProperty("ecoshop:string_times_bought")]
        public double? EcoshopStringTimesBought { get; set; }

        [JsonProperty("ecoskills:dazzle")]
        public double? EcoskillsDazzle { get; set; }

        [JsonProperty("ecoskills:alchemy_xp")]
        public double? EcoskillsAlchemyXp { get; set; }

        [JsonProperty("ecoshop:enchantedbook_cubism_times_bought")]
        public double? EcoshopEnchantedbookCubismTimesBought { get; set; }

        [JsonProperty("ecoshop:enchantedbook_repairing_times_bought")]
        public double? EcoshopEnchantedbookRepairingTimesBought { get; set; }

        [JsonProperty("ecoshop:obsidian_times_bought")]
        public double? EcoshopObsidianTimesBought { get; set; }

        [JsonProperty("ecoshop:enchantedbook_poisonivy_times_bought")]
        public double? EcoshopEnchantedbookPoisonivyTimesBought { get; set; }

        [JsonProperty("ecoshop:honey_block_times_bought")]
        public double? EcoshopHoneyBlockTimesBought { get; set; }

        [JsonProperty("ecoshop:netherite_block_times_bought")]
        public double? EcoshopNetheriteBlockTimesBought { get; set; }

        [JsonProperty("ecoshop:copper_block_times_bought")]
        public double? EcoshopCopperBlockTimesBought { get; set; }

        [JsonProperty("ecoshop:oak_log_times_bought")]
        public double? EcoshopOakLogTimesBought { get; set; }

        [JsonProperty("ecoskills:mystic_resilience")]
        public double? EcoskillsMysticResilience { get; set; }

        [JsonProperty("ecoshop:quartz_block_times_bought")]
        public double? EcoshopQuartzBlockTimesBought { get; set; }

        [JsonProperty("ecoshop:enchantedbook_charge_times_bought")]
        public double? EcoshopEnchantedbookChargeTimesBought { get; set; }

        [JsonProperty("ecoskills:efficient_brewing")]
        public double? EcoskillsEfficientBrewing { get; set; }

        [JsonProperty("ecoskills:fishing")]
        public double? EcoskillsFishing { get; set; }

        [JsonProperty("ecoshop:netherite_ingot_times_bought")]
        public double? EcoshopNetheriteIngotTimesBought { get; set; }

        [JsonProperty("ecoskills:eye_of_the_depths")]
        public double? EcoskillsEyeOfTheDepths { get; set; }

        [JsonProperty("ecoshop:enchantedbook_netheraffinity_times_bought")]
        public double? EcoshopEnchantedbookNetheraffinityTimesBought { get; set; }

        [JsonProperty("ecoshop:rotten_flesh_times_bought")]
        public double? EcoshopRottenFleshTimesBought { get; set; }

        [JsonProperty("ecoskills:dodging")]
        public double? EcoskillsDodging { get; set; }

        [JsonProperty("ecoshop:glistering_melon_slice_times_bought")]
        public double? EcoshopGlisteringMelonSliceTimesBought { get; set; }

        [JsonProperty("ecoshop:gunpowder_times_bought")]
        public double? EcoshopGunpowderTimesBought { get; set; }

        [JsonProperty("ecoquests:quest_daily_quest_example_started_time")]
        public double? EcoquestsQuestDailyQuestExampleStartedTime { get; set; }

        [JsonProperty("ecoshop:ink_sac_times_bought")]
        public double? EcoshopInkSacTimesBought { get; set; }

        [JsonProperty("ecoshop:enchantedbook_flashbang_times_bought")]
        public double? EcoshopEnchantedbookFlashbangTimesBought { get; set; }

        [JsonProperty("ecoshop:enchantedbook_blockbreather_times_bought")]
        public double? EcoshopEnchantedbookBlockbreatherTimesBought { get; set; }

        [JsonProperty("ecoshop:red_sand_times_bought")]
        public double? EcoshopRedSandTimesBought { get; set; }

        [JsonProperty("ecoshop:mycelium_times_bought")]
        public double? EcoshopMyceliumTimesBought { get; set; }

        [JsonProperty("ecoshop:glass_times_bought")]
        public double? EcoshopGlassTimesBought { get; set; }

        [JsonProperty("ecoshop:enchantedbook_ninja_times_bought")]
        public double? EcoshopEnchantedbookNinjaTimesBought { get; set; }

        [JsonProperty("ecoskills:craftsmanship")]
        public double? EcoskillsCraftsmanship { get; set; }

        [JsonProperty("ecoskills:fishing_xp")]
        public double? EcoskillsFishingXp { get; set; }

        [JsonProperty("ecoskills:crit_chance")]
        public double? EcoskillsCritChance { get; set; }

        [JsonProperty("ecoshop:stone_times_bought")]
        public double? EcoshopStoneTimesBought { get; set; }

        [JsonProperty("ecoshop:enchantedbook_featherstep_times_bought")]
        public double? EcoshopEnchantedbookFeatherstepTimesBought { get; set; }

        [JsonProperty("ecoshop:enchantedbook_excavation_times_bought")]
        public double? EcoshopEnchantedbookExcavationTimesBought { get; set; }

        [JsonProperty("ecoshop:enchantedbook_shulkerharvest_times_bought")]
        public double? EcoshopEnchantedbookShulkerharvestTimesBought { get; set; }

        [JsonProperty("ecoshop:enchantedbook_dynamite_times_bought")]
        public double? EcoshopEnchantedbookDynamiteTimesBought { get; set; }

        [JsonProperty("ecoshop:daylight_detector_times_bought")]
        public double? EcoshopDaylightDetectorTimesBought { get; set; }

        [JsonProperty("ecoshop:enchantedbook_blastmining_times_bought")]
        public double? EcoshopEnchantedbookBlastminingTimesBought { get; set; }

        [JsonProperty("ecoskills:exploration_xp")]
        public double? EcoskillsExplorationXp { get; set; }

        [JsonProperty("ecoshop:lapis_lazuli_times_bought")]
        public double? EcoshopLapisLazuliTimesBought { get; set; }

        [JsonProperty("ecoshop:nether_star_times_bought")]
        public double? EcoshopNetherStarTimesBought { get; set; }

        [JsonProperty("ecoshop:enchantedbook_goliath_times_bought")]
        public double? EcoshopEnchantedbookGoliathTimesBought { get; set; }

        [JsonProperty("ecoskills:combat")]
        public double? EcoskillsCombat { get; set; }

        [JsonProperty("ecoskills:bountiful_harvest")]
        public double? EcoskillsBountifulHarvest { get; set; }

        [JsonProperty("ecoshop:acacia_log_times_bought")]
        public double? EcoshopAcaciaLogTimesBought { get; set; }

        [JsonProperty("ecoshop:wither_skeleton_skull_times_bought")]
        public double? EcoshopWitherSkeletonSkullTimesBought { get; set; }

        [JsonProperty("ecoshop:jungle_log_times_bought")]
        public double? EcoshopJungleLogTimesBought { get; set; }

        [JsonProperty("ecoshop:enchantedbook_foraging_times_bought")]
        public double? EcoshopEnchantedbookForagingTimesBought { get; set; }

        [JsonProperty("ecoshop:enchantedbook_introversion_times_bought")]
        public double? EcoshopEnchantedbookIntroversionTimesBought { get; set; }

        [JsonProperty("ecoshop:enchantedbook_abrasion_times_bought")]
        public double? EcoshopEnchantedbookAbrasionTimesBought { get; set; }

        [JsonProperty("ecoskills:strength")]
        public double? EcoskillsStrength { get; set; }

        [JsonProperty("ecoquests:quest_daily_quest_example_completed_time")]
        public double? EcoquestsQuestDailyQuestExampleCompletedTime { get; set; }

        [JsonProperty("ecoshop:enchantedbook_netherprospector_times_bought")]
        public double? EcoshopEnchantedbookNetherprospectorTimesBought { get; set; }

        [JsonProperty("ecoskills:serrated_strikes")]
        public double? EcoskillsSerratedStrikes { get; set; }

        [JsonProperty("ecoshop:enchantedbook_shura_times_bought")]
        public double? EcoshopEnchantedbookShuraTimesBought { get; set; }

        [JsonProperty("ecoshop:lever_times_bought")]
        public double? EcoshopLeverTimesBought { get; set; }

        [JsonProperty("ecoshop:enchantedbook_rebounding_times_bought")]
        public double? EcoshopEnchantedbookReboundingTimesBought { get; set; }

        [JsonProperty("ecoshop:lead_times_bought")]
        public double? EcoshopLeadTimesBought { get; set; }

        [JsonProperty("ecoskills:bravery")]
        public double? EcoskillsBravery { get; set; }

        [JsonProperty("ecoshop:spider_eye_times_bought")]
        public double? EcoshopSpiderEyeTimesBought { get; set; }

        [JsonProperty("ecoskills:versatile_tools")]
        public double? EcoskillsVersatileTools { get; set; }

        [JsonProperty("ecoquests:daily_quest_example_task_break_stone_xp_required")]
        public double? EcoquestsDailyQuestExampleTaskBreakStoneXpRequired { get; set; }

        [JsonProperty("ecoshop:enchantedbook_caffeinated_times_bought")]
        public double? EcoshopEnchantedbookCaffeinatedTimesBought { get; set; }

        [JsonProperty("ecoshop:sticky_piston_times_bought")]
        public double? EcoshopStickyPistonTimesBought { get; set; }

        [JsonProperty("ecoshop:enchantedbook_enderslayer_times_bought")]
        public double? EcoshopEnchantedbookEnderslayerTimesBought { get; set; }

        [JsonProperty("ecoshop:enchantedbook_getaway_times_bought")]
        public double? EcoshopEnchantedbookGetawayTimesBought { get; set; }

        [JsonProperty("ecoshop:enchantedbook_criticals_times_bought")]
        public double? EcoshopEnchantedbookCriticalsTimesBought { get; set; }

        [JsonProperty("ecoshop:ghast_tear_times_bought")]
        public double? EcoshopGhastTearTimesBought { get; set; }

        [JsonProperty("ecoshop:enchantedbook_skullpuncture_times_bought")]
        public double? EcoshopEnchantedbookSkullpunctureTimesBought { get; set; }

        [JsonProperty("ecoskills:mining_xp")]
        public double? EcoskillsMiningXp { get; set; }

        [JsonProperty("ecoshop:enchantedbook_oneforall_times_bought")]
        public double? EcoshopEnchantedbookOneforallTimesBought { get; set; }

        [JsonProperty("ecoskills:farming_xp")]
        public double? EcoskillsFarmingXp { get; set; }

        [JsonProperty("ecoshop:enchantedbook_blackout_times_bought")]
        public double? EcoshopEnchantedbookBlackoutTimesBought { get; set; }

        [JsonProperty("ecoshop:enchantedbook_brightness_times_bought")]
        public double? EcoshopEnchantedbookBrightnessTimesBought { get; set; }

        [JsonProperty("ecoshop:enchantedbook_bleed_times_bought")]
        public double? EcoshopEnchantedbookBleedTimesBought { get; set; }

        [JsonProperty("ecoshop:feather_times_bought")]
        public double? EcoshopFeatherTimesBought { get; set; }

        [JsonProperty("ecoshop:leather_times_bought")]
        public double? EcoshopLeatherTimesBought { get; set; }

        [JsonProperty("ecoshop:andesite_times_bought")]
        public double? EcoshopAndesiteTimesBought { get; set; }

        [JsonProperty("ecoshop:enchantedbook_replenish_times_bought")]
        public double? EcoshopEnchantedbookReplenishTimesBought { get; set; }

        [JsonProperty("ecoquests:quest_daily_quest_example_has_completed")]
        public bool? EcoquestsQuestDailyQuestExampleHasCompleted { get; set; }

        [JsonProperty("ecoshop:enchantedbook_contagion_times_bought")]
        public double? EcoshopEnchantedbookContagionTimesBought { get; set; }

        [JsonProperty("talismans:talisman_bag")]
        public string[]? TalismansTalismanBag { get; set; }

        [JsonProperty("ecoskills:combat_xp")]
        public double? EcoskillsCombatXp { get; set; }

        [JsonProperty("ecoshop:nether_bricks_times_bought")]
        public double? EcoshopNetherBricksTimesBought { get; set; }

        [JsonProperty("ecoshop:bricks_times_bought")]
        public double? EcoshopBricksTimesBought { get; set; }

        [JsonProperty("ecoshop:hopper_times_bought")]
        public double? EcoshopHopperTimesBought { get; set; }

        [JsonProperty("ecoshop:honey_bottle_times_bought")]
        public double? EcoshopHoneyBottleTimesBought { get; set; }

        [JsonProperty("ecoshop:emerald_block_times_bought")]
        public double? EcoshopEmeraldBlockTimesBought { get; set; }

        [JsonProperty("ecoshop:podzol_times_bought")]
        public double? EcoshopPodzolTimesBought { get; set; }

        [JsonProperty("ecoshop:coarse_dirt_times_bought")]
        public double? EcoshopCoarseDirtTimesBought { get; set; }

        [JsonProperty("ecoshop:end_stone_bricks_times_bought")]
        public double? EcoshopEndStoneBricksTimesBought { get; set; }

        [JsonProperty("ecoskills:wisdom")]
        public double? EcoskillsWisdom { get; set; }

        [JsonProperty("ecoshop:ice_times_bought")]
        public double? EcoshopIceTimesBought { get; set; }

        [JsonProperty("ecoskills:overcompensation")]
        public double? EcoskillsOvercompensation { get; set; }

        [JsonProperty("ecoshop:prismarine_shard_times_bought")]
        public double? EcoshopPrismarineShardTimesBought { get; set; }

        [JsonProperty("ecoskills:seamless_movement")]
        public double? EcoskillsSeamlessMovement { get; set; }

        [JsonProperty("ecoshop:diamond_block_times_bought")]
        public double? EcoshopDiamondBlockTimesBought { get; set; }

        [JsonProperty("ecoskills:endangering")]
        public double? EcoskillsEndangering { get; set; }

        [JsonProperty("ecoshop:sea_lantern_times_bought")]
        public double? EcoshopSeaLanternTimesBought { get; set; }

        [JsonProperty("ecoskills:gain_sound_enabled")]
        public bool? EcoskillsGainSoundEnabled { get; set; }

        [JsonProperty("ecoskills:ferocity")]
        public double? EcoskillsFerocity { get; set; }

        [JsonProperty("ecoshop:coal_times_bought")]
        public double? EcoshopCoalTimesBought { get; set; }

        [JsonProperty("ecoshop:spruce_log_times_bought")]
        public double? EcoshopSpruceLogTimesBought { get; set; }

        [JsonProperty("ecoshop:enchantedbook_frost_times_bought")]
        public double? EcoshopEnchantedbookFrostTimesBought { get; set; }

        [JsonProperty("ecoshop:gold_ingot_times_bought")]
        public double? EcoshopGoldIngotTimesBought { get; set; }

        [JsonProperty("ecoenchants:soulbound_items")]
        public object[] EcoenchantsSoulboundItems { get; set; }

        [JsonProperty("ecoshop:redstone_lamp_times_bought")]
        public double? EcoshopRedstoneLampTimesBought { get; set; }

        [JsonProperty("ecoshop:soul_sand_times_bought")]
        public double? EcoshopSoulSandTimesBought { get; set; }

        [JsonProperty("ecoshop:enchantedbook_finishing_times_bought")]
        public double? EcoshopEnchantedbookFinishingTimesBought { get; set; }

        [JsonProperty("ecoskills:actionbar_enabled")]
        public bool? EcoskillsActionbarEnabled { get; set; }

        [JsonProperty("ecoshop:granite_times_bought")]
        public double? EcoshopGraniteTimesBought { get; set; }

        [JsonProperty("ecoskills:golden_yield")]
        public double? EcoskillsGoldenYield { get; set; }

        [JsonProperty("ecoskills:accelerated_escape")]
        public double? EcoskillsAcceleratedEscape { get; set; }

        [JsonProperty("ecoshop:gold_block_times_bought")]
        public double? EcoshopGoldBlockTimesBought { get; set; }

        [JsonProperty("ecoquests:daily_quest_example_task_break_stone_xp")]
        public double? EcoquestsDailyQuestExampleTaskBreakStoneXp { get; set; }

        [JsonProperty("ecoshop:lapis_block_times_bought")]
        public double? EcoshopLapisBlockTimesBought { get; set; }

        [JsonProperty("ecoshop:ender_pearl_times_bought")]
        public double? EcoshopEnderPearlTimesBought { get; set; }

        [JsonProperty("ecoskills:acrobatics")]
        public double? EcoskillsAcrobatics { get; set; }

        [JsonProperty("ecoshop:blaze_rod_times_bought")]
        public double? EcoshopBlazeRodTimesBought { get; set; }

        [JsonProperty("ecoshop:nautilus_shell_times_bought")]
        public double? EcoshopNautilusShellTimesBought { get; set; }

        [JsonProperty("ecoskills:mining")]
        public double? EcoskillsMining { get; set; }

        [JsonProperty("ecoshop:redstone_block_times_bought")]
        public double? EcoshopRedstoneBlockTimesBought { get; set; }

        [JsonProperty("ecoenchants:descriptions_enabled")]
        public bool? EcoenchantsDescriptionsEnabled { get; set; }

        [JsonProperty("ecoshop:comparator_times_bought")]
        public double? EcoshopComparatorTimesBought { get; set; }

        [JsonProperty("ecoshop:red_nether_bricks_times_bought")]
        public double? EcoshopRedNetherBricksTimesBought { get; set; }

        [JsonProperty("ecoshop:netherrack_times_bought")]
        public double? EcoshopNetherrackTimesBought { get; set; }

        [JsonProperty("ecoshop:enchantedbook_rapid_times_bought")]
        public double? EcoshopEnchantedbookRapidTimesBought { get; set; }

        [JsonProperty("ecoshop:end_stone_times_bought")]
        public double? EcoshopEndStoneTimesBought { get; set; }

        [JsonProperty("ecoskills:speed")]
        public double? EcoskillsSpeed { get; set; }

        [JsonProperty("ecoshop:dark_prismarine_times_bought")]
        public double? EcoshopDarkPrismarineTimesBought { get; set; }

        [JsonProperty("ecoskills:attack_speed")]
        public double? EcoskillsAttackSpeed { get; set; }

        [JsonProperty("ecoshop:slime_ball_times_bought")]
        public double? EcoshopSlimeBallTimesBought { get; set; }

        [JsonProperty("ecoshop:mossy_stone_bricks_times_bought")]
        public double? EcoshopMossyStoneBricksTimesBought { get; set; }

        [JsonProperty("ecoshop:diorite_times_bought")]
        public double? EcoshopDioriteTimesBought { get; set; }

        [JsonProperty("ecopets:active_pet")]
        public string? EcopetsActivePet { get; set; }

        [JsonProperty("ecoshop:enchantedbook_adrenaline_times_bought")]
        public double? EcoshopEnchantedbookAdrenalineTimesBought { get; set; }

        [JsonProperty("ecoshop:redstone_torch_times_bought")]
        public double? EcoshopRedstoneTorchTimesBought { get; set; }

        [JsonProperty("ecoshop:enchantedbook_bosshunter_times_bought")]
        public double? EcoshopEnchantedbookBosshunterTimesBought { get; set; }

        [JsonProperty("ecoshop:dark_oak_log_times_bought")]
        public double? EcoshopDarkOakLogTimesBought { get; set; }

        [JsonProperty("ecoshop:enchantedbook_carve_times_bought")]
        public double? EcoshopEnchantedbookCarveTimesBought { get; set; }

        [JsonProperty("ecoshop:emerald_times_bought")]
        public double? EcoshopEmeraldTimesBought { get; set; }

        [JsonProperty("ecoskills:armory_xp")]
        public double? EcoskillsArmoryXp { get; set; }

        [JsonProperty("ecoskills:alchemy")]
        public double? EcoskillsAlchemy { get; set; }

        [JsonProperty("ecoskills:potionmaster")]
        public double? EcoskillsPotionmaster { get; set; }

        [JsonProperty("ecoshop:enchantedbook_jumpshot_times_bought")]
        public double? EcoshopEnchantedbookJumpshotTimesBought { get; set; }

        [JsonProperty("ecoshop:iron_block_times_bought")]
        public double? EcoshopIronBlockTimesBought { get; set; }

        [JsonProperty("ecoquests:daily_quest_example_task_break_stone_has_completed")]
        public bool? EcoquestsDailyQuestExampleTaskBreakStoneHasCompleted { get; set; }

        [JsonProperty("ecoskills:crit_damage")]
        public double? EcoskillsCritDamage { get; set; }

        [JsonProperty("ecoshop:purpur_block_times_bought")]
        public double? EcoshopPurpurBlockTimesBought { get; set; }

        [JsonProperty("ecoshop:copper_ingot_times_bought")]
        public double? EcoshopCopperIngotTimesBought { get; set; }

        [JsonProperty("ecoshop:shulker_shell_times_bought")]
        public double? EcoshopShulkerShellTimesBought { get; set; }

        [JsonProperty("ecoshop:enchantedbook_lifesteal_times_bought")]
        public double? EcoshopEnchantedbookLifestealTimesBought { get; set; }

        [JsonProperty("ecoskills:defense")]
        public double? EcoskillsDefense { get; set; }

        [JsonProperty("ecoshop:enchantedbook_dexterity_times_bought")]
        public double? EcoshopEnchantedbookDexterityTimesBought { get; set; }

        [JsonProperty("ecoshop:enchantedbook_rocketsaver_times_bought")]
        public double? EcoshopEnchantedbookRocketsaverTimesBought { get; set; }

        [JsonProperty("ecoshop:enchantedbook_firststrike_times_bought")]
        public double? EcoshopEnchantedbookFirststrikeTimesBought { get; set; }

        [JsonProperty("ecoshop:orange_concrete_powder_times_bought")]
        public double? EcoshopOrangeConcretePowderTimesBought { get; set; }

        [JsonProperty("ecoshop:crimson_stem_times_bought")]
        public double? EcoshopCrimsonStemTimesBought { get; set; }

        [JsonProperty("ecoshop:white_terracotta_times_bought")]
        public double? EcoshopWhiteTerracottaTimesBought { get; set; }

        [JsonProperty("ecoshop:beetroot_times_bought")]
        public double? EcoshopBeetrootTimesBought { get; set; }

        [JsonProperty("ecoshop:apple_times_bought")]
        public double? EcoshopAppleTimesBought { get; set; }

        [JsonProperty("ecoshop:white_concrete_powder_times_bought")]
        public double? EcoshopWhiteConcretePowderTimesBought { get; set; }

        [JsonProperty("ecoshop:black_dye_times_bought")]
        public double? EcoshopBlackDyeTimesBought { get; set; }

        [JsonProperty("ecoshop:diamond_axe_times_bought")]
        public double? EcoshopDiamondAxeTimesBought { get; set; }

        [JsonProperty("ecoshop:light_blue_stained_glass_times_bought")]
        public double? EcoshopLightBlueStainedGlassTimesBought { get; set; }

        [JsonProperty("ecoshop:enchantedbook_wyvern_times_bought")]
        public double? EcoshopEnchantedbookWyvernTimesBought { get; set; }

        [JsonProperty("ecoshop:yellow_dye_times_bought")]
        public double? EcoshopYellowDyeTimesBought { get; set; }

        [JsonProperty("ecoshop:cooked_porkchop_times_bought")]
        public double? EcoshopCookedPorkchopTimesBought { get; set; }

        [JsonProperty("ecoshop:wheat_times_bought")]
        public double? EcoshopWheatTimesBought { get; set; }

        [JsonProperty("ecoshop:light_blue_concrete_times_bought")]
        public double? EcoshopLightBlueConcreteTimesBought { get; set; }

        [JsonProperty("ecoshop:cobbled_deepslate_times_bought")]
        public double? EcoshopCobbledDeepslateTimesBought { get; set; }

        [JsonProperty("ecoshop:magenta_stained_glass_times_bought")]
        public double? EcoshopMagentaStainedGlassTimesBought { get; set; }

        [JsonProperty("ecoshop:light_gray_dye_times_bought")]
        public double? EcoshopLightGrayDyeTimesBought { get; set; }

        [JsonProperty("ecoshop:orange_stained_glass_times_bought")]
        public double? EcoshopOrangeStainedGlassTimesBought { get; set; }

        [JsonProperty("ecoshop:enchantedbook_vitality_times_bought")]
        public double? EcoshopEnchantedbookVitalityTimesBought { get; set; }

        [JsonProperty("ecoshop:cooked_beef_times_bought")]
        public double? EcoshopCookedBeefTimesBought { get; set; }

        [JsonProperty("ecoshop:baked_potato_times_bought")]
        public double? EcoshopBakedPotatoTimesBought { get; set; }

        [JsonProperty("ecoshop:cobblestone_times_bought")]
        public double? EcoshopCobblestoneTimesBought { get; set; }

        [JsonProperty("ecoshop:bow_times_bought")]
        public double? EcoshopBowTimesBought { get; set; }

        [JsonProperty("ecoshop:blue_dye_times_bought")]
        public double? EcoshopBlueDyeTimesBought { get; set; }

        [JsonProperty("ecoshop:jungle_leaves_times_bought")]
        public double? EcoshopJungleLeavesTimesBought { get; set; }

        [JsonProperty("ecoshop:firework_rocket_times_bought")]
        public double? EcoshopFireworkRocketTimesBought { get; set; }

        [JsonProperty("ecoshop:enchantedbook_wound_times_bought")]
        public double? EcoshopEnchantedbookWoundTimesBought { get; set; }

        [JsonProperty("ecoshop:saddle_times_bought")]
        public double? EcoshopSaddleTimesBought { get; set; }

        [JsonProperty("ecoshop:diamond_helmet_times_bought")]
        public double? EcoshopDiamondHelmetTimesBought { get; set; }

        [JsonProperty("ecoshop:white_stained_glass_times_bought")]
        public double? EcoshopWhiteStainedGlassTimesBought { get; set; }

        [JsonProperty("ecoshop:enchantedbook_veinminer_times_bought")]
        public double? EcoshopEnchantedbookVeinminerTimesBought { get; set; }

        [JsonProperty("ecoshop:enchantedbook_soulstorm_times_bought")]
        public double? EcoshopEnchantedbookSoulstormTimesBought { get; set; }

        [JsonProperty("ecoshop:cooked_mutton_times_bought")]
        public double? EcoshopCookedMuttonTimesBought { get; set; }

        [JsonProperty("ecoshop:diamond_pickaxe_times_bought")]
        public double? EcoshopDiamondPickaxeTimesBought { get; set; }

        [JsonProperty("ecoshop:iron_axe_times_bought")]
        public double? EcoshopIronAxeTimesBought { get; set; }

        [JsonProperty("ecoshop:acacia_sapling_times_bought")]
        public double? EcoshopAcaciaSaplingTimesBought { get; set; }

        [JsonProperty("ecoshop:cyan_dye_times_bought")]
        public double? EcoshopCyanDyeTimesBought { get; set; }

        [JsonProperty("ecoshop:deepslate_times_bought")]
        public double? EcoshopDeepslateTimesBought { get; set; }

        [JsonProperty("ecoshop:light_blue_dye_times_bought")]
        public double? EcoshopLightBlueDyeTimesBought { get; set; }

        [JsonProperty("ecoshop:diamond_hoe_times_bought")]
        public double? EcoshopDiamondHoeTimesBought { get; set; }

        [JsonProperty("ecoshop:orange_wool_times_bought")]
        public double? EcoshopOrangeWoolTimesBought { get; set; }

        [JsonProperty("ecoshop:oak_leaves_times_bought")]
        public double? EcoshopOakLeavesTimesBought { get; set; }

        [JsonProperty("ecoshop:dark_oak_sapling_times_bought")]
        public double? EcoshopDarkOakSaplingTimesBought { get; set; }

        [JsonProperty("ecoshop:shroomlight_times_bought")]
        public double? EcoshopShroomlightTimesBought { get; set; }

        [JsonProperty("ecoshop:magenta_wool_times_bought")]
        public double? EcoshopMagentaWoolTimesBought { get; set; }

        [JsonProperty("ecoshop:chicken_times_bought")]
        public double? EcoshopChickenTimesBought { get; set; }

        [JsonProperty("ecoshop:redstone_times_bought")]
        public double? EcoshopRedstoneTimesBought { get; set; }

        [JsonProperty("ecoshop:magenta_concrete_powder_times_bought")]
        public double? EcoshopMagentaConcretePowderTimesBought { get; set; }

        [JsonProperty("ecoshop:magenta_concrete_times_bought")]
        public double? EcoshopMagentaConcreteTimesBought { get; set; }

        [JsonProperty("ecoshop:acacia_leaves_times_bought")]
        public double? EcoshopAcaciaLeavesTimesBought { get; set; }

        [JsonProperty("ecoshop:light_blue_glazed_terracotta_times_bought")]
        public double? EcoshopLightBlueGlazedTerracottaTimesBought { get; set; }

        [JsonProperty("ecoshop:pink_dye_times_bought")]
        public double? EcoshopPinkDyeTimesBought { get; set; }

        [JsonProperty("ecoshop:lime_dye_times_bought")]
        public double? EcoshopLimeDyeTimesBought { get; set; }

        [JsonProperty("ecoshop:diamond_chestplate_times_bought")]
        public double? EcoshopDiamondChestplateTimesBought { get; set; }

        [JsonProperty("ecoshop:crossbow_times_bought")]
        public double? EcoshopCrossbowTimesBought { get; set; }

        [JsonProperty("ecoshop:iron_chestplate_times_bought")]
        public double? EcoshopIronChestplateTimesBought { get; set; }

        [JsonProperty("ecoshop:enchantedbook_thor_times_bought")]
        public double? EcoshopEnchantedbookThorTimesBought { get; set; }

        [JsonProperty("ecoshop:diamond_shovel_times_bought")]
        public double? EcoshopDiamondShovelTimesBought { get; set; }

        [JsonProperty("ecoshop:poppy_times_bought")]
        public double? EcoshopPoppyTimesBought { get; set; }

        [JsonProperty("ecoshop:clay_times_bought")]
        public double? EcoshopClayTimesBought { get; set; }

        [JsonProperty("ecoshop:iron_hoe_times_bought")]
        public double? EcoshopIronHoeTimesBought { get; set; }

        [JsonProperty("ecoshop:iron_boots_times_bought")]
        public double? EcoshopIronBootsTimesBought { get; set; }

        [JsonProperty("ecoshop:grass_times_bought")]
        public double? EcoshopGrassTimesBought { get; set; }

        [JsonProperty("ecoshop:golden_carrot_times_bought")]
        public double? EcoshopGoldenCarrotTimesBought { get; set; }

        [JsonProperty("ecoshop:name_tag_times_bought")]
        public double? EcoshopNameTagTimesBought { get; set; }

        [JsonProperty("ecoshop:iron_helmet_times_bought")]
        public double? EcoshopIronHelmetTimesBought { get; set; }

        [JsonProperty("ecoshop:seagrass_times_bought")]
        public double? EcoshopSeagrassTimesBought { get; set; }

        [JsonProperty("ecoshop:flowering_azalea_times_bought")]
        public double? EcoshopFloweringAzaleaTimesBought { get; set; }

        [JsonProperty("ecoshop:melon_slice_times_bought")]
        public double? EcoshopMelonSliceTimesBought { get; set; }

        [JsonProperty("ecoshop:enchantedbook_snipe_times_bought")]
        public double? EcoshopEnchantedbookSnipeTimesBought { get; set; }

        [JsonProperty("ecoshop:enchantedbook_telekinesis_times_bought")]
        public double? EcoshopEnchantedbookTelekinesisTimesBought { get; set; }

        [JsonProperty("ecoshop:enchantedbook_stun_times_bought")]
        public double? EcoshopEnchantedbookStunTimesBought { get; set; }

        [JsonProperty("ecoshop:brown_dye_times_bought")]
        public double? EcoshopBrownDyeTimesBought { get; set; }

        [JsonProperty("ecoshop:magenta_glazed_terracotta_times_bought")]
        public double? EcoshopMagentaGlazedTerracottaTimesBought { get; set; }

        [JsonProperty("ecoshop:smooth_stone_times_bought")]
        public double? EcoshopSmoothStoneTimesBought { get; set; }

        [JsonProperty("ecoshop:porkchop_times_bought")]
        public double? EcoshopPorkchopTimesBought { get; set; }

        [JsonProperty("ecoshop:light_blue_terracotta_times_bought")]
        public double? EcoshopLightBlueTerracottaTimesBought { get; set; }

        [JsonProperty("ecoshop:crying_obsidian_times_bought")]
        public double? EcoshopCryingObsidianTimesBought { get; set; }

        [JsonProperty("ecoshop:melon_seeds_times_bought")]
        public double? EcoshopMelonSeedsTimesBought { get; set; }

        [JsonProperty("ecoshop:carrot_times_bought")]
        public double? EcoshopCarrotTimesBought { get; set; }

        [JsonProperty("ecoshop:iron_leggings_times_bought")]
        public double? EcoshopIronLeggingsTimesBought { get; set; }

        [JsonProperty("ecoshop:iron_sword_times_bought")]
        public double? EcoshopIronSwordTimesBought { get; set; }

        [JsonProperty("ecoshop:fern_times_bought")]
        public double? EcoshopFernTimesBought { get; set; }

        [JsonProperty("ecoshop:dripstone_block_times_bought")]
        public double? EcoshopDripstoneBlockTimesBought { get; set; }

        [JsonProperty("ecoshop:dark_oak_leaves_times_bought")]
        public double? EcoshopDarkOakLeavesTimesBought { get; set; }

        [JsonProperty("ecoshop:orange_concrete_times_bought")]
        public double? EcoshopOrangeConcreteTimesBought { get; set; }

        [JsonProperty("ecoshop:potato_times_bought")]
        public double? EcoshopPotatoTimesBought { get; set; }

        [JsonProperty("ecoshop:beef_times_bought")]
        public double? EcoshopBeefTimesBought { get; set; }

        [JsonProperty("ecoshop:green_dye_times_bought")]
        public double? EcoshopGreenDyeTimesBought { get; set; }

        [JsonProperty("ecoshop:enchantedbook_stamina_times_bought")]
        public double? EcoshopEnchantedbookStaminaTimesBought { get; set; }

        [JsonProperty("ecoshop:blue_orchid_times_bought")]
        public double? EcoshopBlueOrchidTimesBought { get; set; }

        [JsonProperty("ecoshop:gray_dye_times_bought")]
        public double? EcoshopGrayDyeTimesBought { get; set; }

        [JsonProperty("ecoshop:white_wool_times_bought")]
        public double? EcoshopWhiteWoolTimesBought { get; set; }

        [JsonProperty("ecoshop:trident_times_bought")]
        public double? EcoshopTridentTimesBought { get; set; }

        [JsonProperty("ecoshop:enchantedbook_transmission_times_bought")]
        public double? EcoshopEnchantedbookTransmissionTimesBought { get; set; }

        [JsonProperty("ecoshop:white_glazed_terracotta_times_bought")]
        public double? EcoshopWhiteGlazedTerracottaTimesBought { get; set; }

        [JsonProperty("ecoshop:gravel_times_bought")]
        public double? EcoshopGravelTimesBought { get; set; }

        [JsonProperty("ecoshop:iron_shovel_times_bought")]
        public double? EcoshopIronShovelTimesBought { get; set; }

        [JsonProperty("ecoshop:cooked_chicken_times_bought")]
        public double? EcoshopCookedChickenTimesBought { get; set; }

        [JsonProperty("ecoshop:spruce_leaves_times_bought")]
        public double? EcoshopSpruceLeavesTimesBought { get; set; }

        [JsonProperty("ecoshop:end_rod_times_bought")]
        public double? EcoshopEndRodTimesBought { get; set; }

        [JsonProperty("ecoshop:sandstone_times_bought")]
        public double? EcoshopSandstoneTimesBought { get; set; }

        [JsonProperty("ecoshop:moss_block_times_bought")]
        public double? EcoshopMossBlockTimesBought { get; set; }

        [JsonProperty("ecoshop:shield_times_bought")]
        public double? EcoshopShieldTimesBought { get; set; }

        [JsonProperty("ecoshop:enchantedbook_sparks_times_bought")]
        public double? EcoshopEnchantedbookSparksTimesBought { get; set; }

        [JsonProperty("ecoshop:enchantedbook_wisdom_times_bought")]
        public double? EcoshopEnchantedbookWisdomTimesBought { get; set; }

        [JsonProperty("ecoshop:enchantedbook_vanish_times_bought")]
        public double? EcoshopEnchantedbookVanishTimesBought { get; set; }

        [JsonProperty("ecoshop:orange_terracotta_times_bought")]
        public double? EcoshopOrangeTerracottaTimesBought { get; set; }

        [JsonProperty("ecoshop:birch_sapling_times_bought")]
        public double? EcoshopBirchSaplingTimesBought { get; set; }

        [JsonProperty("ecoshop:light_blue_wool_times_bought")]
        public double? EcoshopLightBlueWoolTimesBought { get; set; }

        [JsonProperty("ecoshop:red_dye_times_bought")]
        public double? EcoshopRedDyeTimesBought { get; set; }

        [JsonProperty("ecoshop:diamond_boots_times_bought")]
        public double? EcoshopDiamondBootsTimesBought { get; set; }

        [JsonProperty("ecoshop:enchantedbook_slaughter_times_bought")]
        public double? EcoshopEnchantedbookSlaughterTimesBought { get; set; }

        [JsonProperty("ecoshop:sea_pickle_times_bought")]
        public double? EcoshopSeaPickleTimesBought { get; set; }

        [JsonProperty("ecoshop:white_concrete_times_bought")]
        public double? EcoshopWhiteConcreteTimesBought { get; set; }

        [JsonProperty("ecoshop:diamond_sword_times_bought")]
        public double? EcoshopDiamondSwordTimesBought { get; set; }

        [JsonProperty("ecoshop:dead_bush_times_bought")]
        public double? EcoshopDeadBushTimesBought { get; set; }

        [JsonProperty("ecoshop:orange_glazed_terracotta_times_bought")]
        public double? EcoshopOrangeGlazedTerracottaTimesBought { get; set; }

        [JsonProperty("ecoshop:enchantedbook_slipstream_times_bought")]
        public double? EcoshopEnchantedbookSlipstreamTimesBought { get; set; }

        [JsonProperty("ecoshop:elytra_times_bought")]
        public double? EcoshopElytraTimesBought { get; set; }

        [JsonProperty("ecoshop:magenta_dye_times_bought")]
        public double? EcoshopMagentaDyeTimesBought { get; set; }

        [JsonProperty("ecoshop:iron_pickaxe_times_bought")]
        public double? EcoshopIronPickaxeTimesBought { get; set; }

        [JsonProperty("ecoshop:enchantedbook_tripleshot_times_bought")]
        public double? EcoshopEnchantedbookTripleshotTimesBought { get; set; }

        [JsonProperty("ecoshop:golden_apple_times_bought")]
        public double? EcoshopGoldenAppleTimesBought { get; set; }

        [JsonProperty("ecoshop:azalea_leaves_times_bought")]
        public double? EcoshopAzaleaLeavesTimesBought { get; set; }

        [JsonProperty("ecoshop:enchantedbook_warpdrive_times_bought")]
        public double? EcoshopEnchantedbookWarpdriveTimesBought { get; set; }

        [JsonProperty("ecoshop:enchantedbook_thrive_times_bought")]
        public double? EcoshopEnchantedbookThriveTimesBought { get; set; }

        [JsonProperty("ecoshop:cactus_times_bought")]
        public double? EcoshopCactusTimesBought { get; set; }

        [JsonProperty("ecoshop:azalea_times_bought")]
        public double? EcoshopAzaleaTimesBought { get; set; }

        [JsonProperty("ecoshop:enchantedbook_soulbound_times_bought")]
        public double? EcoshopEnchantedbookSoulboundTimesBought { get; set; }

        [JsonProperty("ecoshop:light_blue_concrete_powder_times_bought")]
        public double? EcoshopLightBlueConcretePowderTimesBought { get; set; }

        [JsonProperty("ecoshop:warped_stem_times_bought")]
        public double? EcoshopWarpedStemTimesBought { get; set; }

        [JsonProperty("ecoshop:purple_dye_times_bought")]
        public double? EcoshopPurpleDyeTimesBought { get; set; }

        [JsonProperty("ecoshop:diamond_leggings_times_bought")]
        public double? EcoshopDiamondLeggingsTimesBought { get; set; }

        [JsonProperty("ecoshop:oak_sapling_times_bought")]
        public double? EcoshopOakSaplingTimesBought { get; set; }

        [JsonProperty("ecoshop:wheat_seeds_times_bought")]
        public double? EcoshopWheatSeedsTimesBought { get; set; }

        [JsonProperty("ecoshop:jungle_sapling_times_bought")]
        public double? EcoshopJungleSaplingTimesBought { get; set; }

        [JsonProperty("ecoshop:enchantedbook_streamlining_times_bought")]
        public double? EcoshopEnchantedbookStreamliningTimesBought { get; set; }

        [JsonProperty("ecoshop:birch_leaves_times_bought")]
        public double? EcoshopBirchLeavesTimesBought { get; set; }

        [JsonProperty("ecoshop:dandelion_times_bought")]
        public double? EcoshopDandelionTimesBought { get; set; }

        [JsonProperty("ecoshop:spruce_sapling_times_bought")]
        public double? EcoshopSpruceSaplingTimesBought { get; set; }

        [JsonProperty("ecoshop:orange_dye_times_bought")]
        public double? EcoshopOrangeDyeTimesBought { get; set; }

        [JsonProperty("ecoshop:magenta_terracotta_times_bought")]
        public double? EcoshopMagentaTerracottaTimesBought { get; set; }

        [JsonProperty("ecoshop:peony_times_bought")]
        public double? EcoshopPeonyTimesBought { get; set; }

        [JsonProperty("ecoshop:sugar_cane_times_bought")]
        public double? EcoshopSugarCaneTimesBought { get; set; }

        [JsonProperty("ecoshop:allium_times_bought")]
        public double? EcoshopAlliumTimesBought { get; set; }

        [JsonProperty("ecoshop:lily_of_the_valley_times_bought")]
        public double? EcoshopLilyOfTheValleyTimesBought { get; set; }

        [JsonProperty("ecoshop:brown_mushroom_times_bought")]
        public double? EcoshopBrownMushroomTimesBought { get; set; }

        [JsonProperty("ecoshop:pumpkin_times_bought")]
        public double? EcoshopPumpkinTimesBought { get; set; }

        [JsonProperty("ecoshop:bamboo_times_bought")]
        public double? EcoshopBambooTimesBought { get; set; }

        [JsonProperty("ecoshop:sunflower_times_bought")]
        public double? EcoshopSunflowerTimesBought { get; set; }

        [JsonProperty("ecoshop:pink_tulip_times_bought")]
        public double? EcoshopPinkTulipTimesBought { get; set; }

        [JsonProperty("ecoshop:white_tulip_times_bought")]
        public double? EcoshopWhiteTulipTimesBought { get; set; }

        [JsonProperty("ecoshop:red_mushroom_times_bought")]
        public double? EcoshopRedMushroomTimesBought { get; set; }

        [JsonProperty("ecoshop:cornflower_times_bought")]
        public double? EcoshopCornflowerTimesBought { get; set; }

        [JsonProperty("ecoshop:wither_rose_times_bought")]
        public double? EcoshopWitherRoseTimesBought { get; set; }

        [JsonProperty("ecoshop:orange_tulip_times_bought")]
        public double? EcoshopOrangeTulipTimesBought { get; set; }

        [JsonProperty("ecoshop:large_fern_times_bought")]
        public double? EcoshopLargeFernTimesBought { get; set; }

        [JsonProperty("ecoshop:vine_times_bought")]
        public double? EcoshopVineTimesBought { get; set; }

        [JsonProperty("ecoshop:oxeye_daisy_times_bought")]
        public double? EcoshopOxeyeDaisyTimesBought { get; set; }

        [JsonProperty("ecoshop:kelp_times_bought")]
        public double? EcoshopKelpTimesBought { get; set; }

        [JsonProperty("ecoshop:glow_lichen_times_bought")]
        public double? EcoshopGlowLichenTimesBought { get; set; }

        [JsonProperty("ecoshop:lilac_times_bought")]
        public double? EcoshopLilacTimesBought { get; set; }

        [JsonProperty("ecoshop:melon_times_bought")]
        public double? EcoshopMelonTimesBought { get; set; }

        [JsonProperty("ecoshop:rose_bush_times_bought")]
        public double? EcoshopRoseBushTimesBought { get; set; }

        [JsonProperty("ecoshop:nether_wart_times_bought")]
        public double? EcoshopNetherWartTimesBought { get; set; }

        [JsonProperty("ecoshop:tall_grass_times_bought")]
        public double? EcoshopTallGrassTimesBought { get; set; }

        [JsonProperty("ecoshop:red_tulip_times_bought")]
        public double? EcoshopRedTulipTimesBought { get; set; }

        [JsonProperty("ecoshop:lily_pad_times_bought")]
        public double? EcoshopLilyPadTimesBought { get; set; }

        [JsonProperty("ecoshop:cyan_wool_times_bought")]
        public double? EcoshopCyanWoolTimesBought { get; set; }

        [JsonProperty("ecoshop:gray_terracotta_times_bought")]
        public double? EcoshopGrayTerracottaTimesBought { get; set; }

        [JsonProperty("ecoshop:green_concrete_times_bought")]
        public double? EcoshopGreenConcreteTimesBought { get; set; }

        [JsonProperty("ecoshop:light_gray_concrete_powder_times_bought")]
        public double? EcoshopLightGrayConcretePowderTimesBought { get; set; }

        [JsonProperty("ecoshop:black_stained_glass_times_bought")]
        public double? EcoshopBlackStainedGlassTimesBought { get; set; }

        [JsonProperty("ecoshop:gray_concrete_times_bought")]
        public double? EcoshopGrayConcreteTimesBought { get; set; }

        [JsonProperty("ecoshop:yellow_stained_glass_times_bought")]
        public double? EcoshopYellowStainedGlassTimesBought { get; set; }

        [JsonProperty("ecoquests:quest_daily_quest_example_last_reset_time")]
        public double? EcoquestsQuestDailyQuestExampleLastResetTime { get; set; }

        [JsonProperty("ecoshop:light_gray_concrete_times_bought")]
        public double? EcoshopLightGrayConcreteTimesBought { get; set; }

        [JsonProperty("ecoshop:pink_concrete_powder_times_bought")]
        public double? EcoshopPinkConcretePowderTimesBought { get; set; }

        [JsonProperty("ecoshop:blue_glazed_terracotta_times_bought")]
        public double? EcoshopBlueGlazedTerracottaTimesBought { get; set; }

        [JsonProperty("ecoshop:green_stained_glass_times_bought")]
        public double? EcoshopGreenStainedGlassTimesBought { get; set; }

        [JsonProperty("ecoshop:yellow_terracotta_times_bought")]
        public double? EcoshopYellowTerracottaTimesBought { get; set; }

        [JsonProperty("ecoshop:blue_stained_glass_times_bought")]
        public double? EcoshopBlueStainedGlassTimesBought { get; set; }

        [JsonProperty("ecoshop:brown_concrete_powder_times_bought")]
        public double? EcoshopBrownConcretePowderTimesBought { get; set; }

        [JsonProperty("ecoshop:red_terracotta_times_bought")]
        public double? EcoshopRedTerracottaTimesBought { get; set; }

        [JsonProperty("ecoshop:pink_concrete_times_bought")]
        public double? EcoshopPinkConcreteTimesBought { get; set; }

        [JsonProperty("ecoshop:pink_stained_glass_times_bought")]
        public double? EcoshopPinkStainedGlassTimesBought { get; set; }

        [JsonProperty("ecoshop:brown_concrete_times_bought")]
        public double? EcoshopBrownConcreteTimesBought { get; set; }

        [JsonProperty("eco:local_server_id")]
        public Guid? EcoLocalServerId { get; set; }

        [JsonProperty("ecoshop:cyan_terracotta_times_bought")]
        public double? EcoshopCyanTerracottaTimesBought { get; set; }

        [JsonProperty("ecoshop:light_gray_terracotta_times_bought")]
        public double? EcoshopLightGrayTerracottaTimesBought { get; set; }

        [JsonProperty("ecoshop:blue_concrete_times_bought")]
        public double? EcoshopBlueConcreteTimesBought { get; set; }

        [JsonProperty("ecoshop:gray_glazed_terracotta_times_bought")]
        public double? EcoshopGrayGlazedTerracottaTimesBought { get; set; }

        [JsonProperty("ecoshop:light_gray_stained_glass_times_bought")]
        public double? EcoshopLightGrayStainedGlassTimesBought { get; set; }

        [JsonProperty("ecoshop:blue_concrete_powder_times_bought")]
        public double? EcoshopBlueConcretePowderTimesBought { get; set; }

        [JsonProperty("ecoquests:quest_daily_quest_example_tasks")]
        public string[]? EcoquestsQuestDailyQuestExampleTasks { get; set; }

        [JsonProperty("ecoshop:gray_concrete_powder_times_bought")]
        public double? EcoshopGrayConcretePowderTimesBought { get; set; }

        [JsonProperty("ecoshop:blue_wool_times_bought")]
        public double? EcoshopBlueWoolTimesBought { get; set; }

        [JsonProperty("ecoshop:black_terracotta_times_bought")]
        public double? EcoshopBlackTerracottaTimesBought { get; set; }

        [JsonProperty("ecoshop:cyan_concrete_powder_times_bought")]
        public double? EcoshopCyanConcretePowderTimesBought { get; set; }

        [JsonProperty("ecoshop:gray_wool_times_bought")]
        public double? EcoshopGrayWoolTimesBought { get; set; }

        [JsonProperty("ecoshop:black_concrete_times_bought")]
        public double? EcoshopBlackConcreteTimesBought { get; set; }

        [JsonProperty("ecoshop:pink_terracotta_times_bought")]
        public double? EcoshopPinkTerracottaTimesBought { get; set; }

        [JsonProperty("ecoshop:red_glazed_terracotta_times_bought")]
        public double? EcoshopRedGlazedTerracottaTimesBought { get; set; }

        [JsonProperty("ecoshop:brown_glazed_terracotta_times_bought")]
        public double? EcoshopBrownGlazedTerracottaTimesBought { get; set; }

        [JsonProperty("ecoshop:yellow_wool_times_bought")]
        public double? EcoshopYellowWoolTimesBought { get; set; }

        [JsonProperty("ecoshop:lime_concrete_powder_times_bought")]
        public double? EcoshopLimeConcretePowderTimesBought { get; set; }

        [JsonProperty("ecoshop:purple_terracotta_times_bought")]
        public double? EcoshopPurpleTerracottaTimesBought { get; set; }

        [JsonProperty("ecoshop:red_concrete_times_bought")]
        public double? EcoshopRedConcreteTimesBought { get; set; }

        [JsonProperty("ecoshop:lime_glazed_terracotta_times_bought")]
        public double? EcoshopLimeGlazedTerracottaTimesBought { get; set; }

        [JsonProperty("ecoshop:red_stained_glass_times_bought")]
        public double? EcoshopRedStainedGlassTimesBought { get; set; }

        [JsonProperty("ecoshop:black_glazed_terracotta_times_bought")]
        public double? EcoshopBlackGlazedTerracottaTimesBought { get; set; }

        [JsonProperty("ecoshop:cyan_concrete_times_bought")]
        public double? EcoshopCyanConcreteTimesBought { get; set; }

        [JsonProperty("ecoshop:blue_terracotta_times_bought")]
        public double? EcoshopBlueTerracottaTimesBought { get; set; }

        [JsonProperty("ecoshop:purple_concrete_times_bought")]
        public double? EcoshopPurpleConcreteTimesBought { get; set; }

        [JsonProperty("ecoshop:green_concrete_powder_times_bought")]
        public double? EcoshopGreenConcretePowderTimesBought { get; set; }

        [JsonProperty("ecoshop:purple_stained_glass_times_bought")]
        public double? EcoshopPurpleStainedGlassTimesBought { get; set; }

        [JsonProperty("ecoshop:black_wool_times_bought")]
        public double? EcoshopBlackWoolTimesBought { get; set; }

        [JsonProperty("ecoshop:cyan_stained_glass_times_bought")]
        public double? EcoshopCyanStainedGlassTimesBought { get; set; }

        [JsonProperty("ecoshop:lime_concrete_times_bought")]
        public double? EcoshopLimeConcreteTimesBought { get; set; }

        [JsonProperty("ecoshop:green_glazed_terracotta_times_bought")]
        public double? EcoshopGreenGlazedTerracottaTimesBought { get; set; }

        [JsonProperty("ecoshop:gray_stained_glass_times_bought")]
        public double? EcoshopGrayStainedGlassTimesBought { get; set; }

        [JsonProperty("ecoshop:purple_glazed_terracotta_times_bought")]
        public double? EcoshopPurpleGlazedTerracottaTimesBought { get; set; }

        [JsonProperty("boosters:2sell_multiplier_active")]
        public string? Boosters2SellMultiplierActive { get; set; }

        [JsonProperty("ecoshop:yellow_glazed_terracotta_times_bought")]
        public double? EcoshopYellowGlazedTerracottaTimesBought { get; set; }

        [JsonProperty("ecoshop:light_gray_glazed_terracotta_times_bought")]
        public double? EcoshopLightGrayGlazedTerracottaTimesBought { get; set; }

        [JsonProperty("ecoshop:black_concrete_powder_times_bought")]
        public double? EcoshopBlackConcretePowderTimesBought { get; set; }

        [JsonProperty("ecoshop:lime_wool_times_bought")]
        public double? EcoshopLimeWoolTimesBought { get; set; }

        [JsonProperty("ecoshop:pink_glazed_terracotta_times_bought")]
        public double? EcoshopPinkGlazedTerracottaTimesBought { get; set; }

        [JsonProperty("ecoshop:pink_wool_times_bought")]
        public double? EcoshopPinkWoolTimesBought { get; set; }

        [JsonProperty("ecoshop:purple_wool_times_bought")]
        public double? EcoshopPurpleWoolTimesBought { get; set; }

        [JsonProperty("ecoshop:light_gray_wool_times_bought")]
        public double? EcoshopLightGrayWoolTimesBought { get; set; }

        [JsonProperty("ecoshop:brown_terracotta_times_bought")]
        public double? EcoshopBrownTerracottaTimesBought { get; set; }

        [JsonProperty("ecoshop:lime_stained_glass_times_bought")]
        public double? EcoshopLimeStainedGlassTimesBought { get; set; }

        [JsonProperty("ecoshop:brown_stained_glass_times_bought")]
        public double? EcoshopBrownStainedGlassTimesBought { get; set; }

        [JsonProperty("boosters:1_5sell_multiplier_active")]
        public string? Boosters1_5SellMultiplierActive { get; set; }

        [JsonProperty("ecoshop:red_wool_times_bought")]
        public double? EcoshopRedWoolTimesBought { get; set; }

        [JsonProperty("boosters:skill_xp_active")]
        public string? BoostersSkillXpActive { get; set; }

        [JsonProperty("ecoshop:purple_concrete_powder_times_bought")]
        public double? EcoshopPurpleConcretePowderTimesBought { get; set; }

        [JsonProperty("ecoshop:green_terracotta_times_bought")]
        public double? EcoshopGreenTerracottaTimesBought { get; set; }

        [JsonProperty("ecoshop:cyan_glazed_terracotta_times_bought")]
        public double? EcoshopCyanGlazedTerracottaTimesBought { get; set; }

        [JsonProperty("ecoshop:lime_terracotta_times_bought")]
        public double? EcoshopLimeTerracottaTimesBought { get; set; }

        [JsonProperty("ecoshop:brown_wool_times_bought")]
        public double? EcoshopBrownWoolTimesBought { get; set; }

        [JsonProperty("ecoshop:green_wool_times_bought")]
        public double? EcoshopGreenWoolTimesBought { get; set; }

        [JsonProperty("ecoshop:yellow_concrete_times_bought")]
        public double? EcoshopYellowConcreteTimesBought { get; set; }

        [JsonProperty("ecoshop:yellow_concrete_powder_times_bought")]
        public double? EcoshopYellowConcretePowderTimesBought { get; set; }

        [JsonProperty("ecoshop:red_concrete_powder_times_bought")]
        public double? EcoshopRedConcretePowderTimesBought { get; set; }
    }

    public partial class EcoDataAdapter
    {
        public static EcoDataAdapter? FromJson(string json) => JsonConvert.DeserializeObject<EcoDataAdapter>(json, Highgeek.McWebApp.Common.Models.Adapters.EcoData.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this EcoDataAdapter self) => JsonConvert.SerializeObject(self, Highgeek.McWebApp.Common.Models.Adapters.EcoData.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
